### ISSUE TITLE
elastiq does not work with Ubuntu 12.04

### ISSUE THREAD

**Issue by dberzano** [dberzano/elastiq#8]
Due to an old boto version (v2.2.2) we obtain:

```
Can't get list of owned EC2 instances in error: 'EC2Connection' object has no attribute 'get_only_instances'
```

Currently at least boto v2.13 is required. Code should be adapted to work also with such old boto version.
